packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@anthropic-ai/sdk@0.123.0'
  - bullmq@6.3.4
